<a href="https://colab.research.google.com/github/zamman365-glitch/Libraries/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

#1 Addition of the array
print(a+b)

#2 subtraction the array
print(a-b)

#3 Multiplication of the arrays
print(a*b)



[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a=np.array([10,20,30,40])
print(a*5)

[ 50 100 150 200]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
A=np.array([[10,20,30],[40,50,60]])
B=np.array([10,20,30])
print(A+B)

[[20 40 60]
 [50 70 90]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
# Basic Statistical operations perform
arr=np.array([4,78,21,34,100,56])

#1. sum
print(f"Sum is : {arr.sum()}")

#2. Mean
print(f"Mean is : {arr.mean()}")


#3. Min
print(f"Min is : {arr.min()}")

#4. Max
print(f"Max is : {arr.max()}")

#5. Standard deviation
print(f"Standard deviation : {arr.std()} ")

#6. Varaince
print(f"Varaince : {arr.var()}")



Sum is : 293
Mean is : 48.833333333333336
Min is : 4
Max is : 100
Standard deviation : 32.97684372741306 
Varaince : 1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
data=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f"Sum of all : { data.sum()}")
#axis=0 -> columns
#axis=1 -> rows
print(f'Sum of columns:{np.sum(data,axis=0)}')
print(f'Sum of rows:{np.sum(data,axis=1)}')

Sum of all : 450
Sum of columns:[120 150 180]
Sum of rows:[ 60 150 240]
